### ISSUE TITLE
Push the relevant upstream tags to the repo

### ISSUE THREAD

**Issue by chutzimir** [microsoft/WSL2-Linux-Kernel#10]
Could you push at least the upstream tags you are based on to this repo? This will make it easier to see the changes done in this repo at https://github.com/microsoft/WSL2-Linux-Kernel/compare/v4.19.57...master instead of https://github.com/microsoft/WSL2-Linux-Kernel/compare/1a05924366694d17a36e6b086d5bba1a8d74b977...master.

**Comment by sashalevin** [comment]
Sure, now pushed.
