### ISSUE TITLE
Is there any plan to support systemd?

### ISSUE THREAD

**Issue by lining2020** [microsoft/WSL2-Linux-Kernel#104]
Hi wsl team:

Systemd is now the mainstream init daemon of most (new) linux systems.
Many polular projects like docker, kubernetes relay on systemd to manage the service.

So, is there any plan to support systemd?

**Comment by lining2020** [comment]
We are also used to systemd. 😊

**Comment by zacharyrs** [comment]
Somewhat off-topic, but you might want to look at [genie](https://github.com/arkane-systems/genie), or a shameless plug for [djinn](https://github.com/zacharyrs/djinn). They let you 'bottle' systemd.

**Comment by TBBle** [comment]
Not really a kernel issue, the kernel works with systemd. See https://github.com/microsoft/WSL/issues/994 for the current tracking issue.
