### ISSUE TITLE
Steps to Test GPU (Nvidia CUDA and/or WSL GPU Preview)

### ISSUE THREAD

**Issue by ningacoding** [microsoft/WSL2-Linux-Kernel#118]
What are the steps to make run a Preview Build of Nvidia CUDA and/or WSL GPU kernel?

I've readed that WSL GPU is available in Preview mode (or early access) but after installed CUDA and build the latest (no estable) kernel from this repository, i'm not able to see GPU changes (enabled in this case).

Just for testing porpuses, i know it still in Development.

Thanks.

**Comment by Biswa96** [comment]
It's not even public, so wait.

**Comment by ne0ark** [comment]
I thought 4.19.121 + v1.2.0-rc.1 was all you needed to enable cuda support.

**Comment by ningacoding** [comment]
"v1.2.0-rc.1"
is the versión of CUDA? because i'm having v11

```
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Wed_May__6_19:10:02_Pacific_Daylight_Time_2020
Cuda compilation tools, release 11.0, V11.0.167
Build cuda_11.0_bu.relgpu_drvr445TC445_37.28358933_0
```

**Comment by levicki** [comment]
https://docs.nvidia.com/cuda/wsl-user-guide/index.html

**Comment by ningacoding** [comment]
WSL2 with GPU support was released on 17 June, thank you.

**Comment by csash7** [comment]
https://ubuntu.com/blog/getting-started-with-cuda-on-ubuntu-on-wsl-2
