### ISSUE TITLE
question for  localhost  in wsl 2

### ISSUE THREAD

**Issue by infdahai** [microsoft/WSL2-Linux-Kernel#12]
I have a question. 

My situation:
  I want to install  nginx + php and deploy it in wsl 2.  So can I use some method to start browser to see the web page running on the localhost url ?

**Comment by kodeclan** [comment]
I believe this does work.
From within WSL2, you can run: `curl localhost`

Now, if you want to have localhost access from Windows as well, you will have to upgrade to Windows 18945 release (https://devblogs.microsoft.com/commandline/whats-new-for-wsl-in-insiders-preview-build-18945/)

Hope that helps

**Comment by Lips7** [comment]
but it still won't work in some special cases

**Comment by kinglionsz** [comment]
curl localhost
curl: (7) Failed to connect to localhost port 80: Connection refused

platform: wsl😥
