### ISSUE TITLE
[Question] Windows 10 2004 and WSL 2 status

### ISSUE THREAD

**Issue by levicki** [microsoft/WSL2-Linux-Kernel#126]
Since the NVIDIA GPU integration for WSL is now available and build 19041 (Windows 10 2004) is listed as a minimum requirement, I have attempted to install WSL 2 by following instructions available [here](https://docs.microsoft.com/en-us/windows/wsl/install-win10).

I have managed to install it, but I did not get the update 4.9.121 offered on Windows Update after multiple checks so I downloaded and installed it manually from the Update Catalog.

With that in mind I have the following questions:

1. Is there some condition that needs to be met for this kernel update to be offered through WU?
2. If I installed WSL 2 MSI package manually, will future updates through Windows Update work?
3. Is there a way to check from WSL whether host GPU driver supports required features?

**Comment by TBBle** [comment]
GPU Compute, Windows Update/[Update Catalog](https://www.catalog.update.microsoft.com/Search.aspx?q=%22Windows%20Subsystem%20for%20Linux%20Update%22) support for the Kernel, and the `wsl --update` command that goes with it (rather than via the installer on https://aka.ms/wsl2kernel) are not part of the Windows 10 2004 release (build [19041](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-19041), as they are from a later build, [20150](https://docs.microsoft.com/en-us/windows/wsl/release-notes#build-20150).

So as far as I understand, you'll need to move to the [Windows Insider Dev Channel](https://blogs.windows.com/windowsexperience/2020/06/17/announcing-windows-10-insider-preview-build-20150/) to get WSL2 GPU compute now. Or at least that's my understanding of [the blog post](https://devblogs.microsoft.com/commandline/gpu-compute-wsl-install-and-wsl-update-arrive-in-the-windows-insiders-fast-ring-for-the-windows-subsystem-for-linux/).

The earlier [blog post](https://devblogs.microsoft.com/commandline/wsl2-will-be-generally-available-in-windows-10-version-2004/) does say that if you install the kernel from the MSI download, the Windows Update flow will take over from there once it is deployed. I am assuming it's not ready yet, since I also am not being offered an update from 4.19.104 to 4.19.121.

**Comment by levicki** [comment]
@TBBle I understand that `wsl --update` functionality is present only in the Insider builds.

However, I was under impression that build 19041 (aka Windows 10 2004) together with kernel 4.19.121 and NVIDIA driver 455.38 is a supported combination.

Unfortunately, aside from actually trying to run a GPU compute workload from within WSL 2, there seems to be no easy way to check whether GPU compute is enabled and functional.

From looking at the GitHub kernel release page it seems that 4.19.121 is still marked as pre-release so that might explain why it is not pushed through Windows Update once you manually install 4.19.104 which is the minimum required for WSL 2.

Finally, it is also worth noting that the download link at https://aka.ms/wsl2kernel despite its claim does not actually point to the latest kernel version.

**Comment by TBBle** [comment]
[Ubuntu's blog post on CUDA support](https://ubuntu.com/blog/getting-started-with-cuda-on-ubuntu-on-wsl-2) also states you need to be on Winows 10 build 20150 from the Dev Channel. [NVIDIA's post on CUDA support](https://devblogs.nvidia.com/announcing-cuda-on-windows-subsystem-for-linux-2/) suggests they tested on build 20149, and [Intel's beta driver page](https://downloadcenter.intel.com/download/29526) lists build 20145. Neither [AMD's blog post](https://community.amd.com/community/radeon-pro-graphics/blog/2020/06/17/announcing-amd-support-for-gpu-accelerated-machine-learning-training-on-windows-10) nor [driver preview](https://www.amd.com/en/support/kb/release-notes/rn-rad-win-wsl-support) mentions version requirements, but the former refers back to the [MS blog post](https://blogs.windows.com/windowsdeveloper/2020/06/17/gpu-accelerated-ml-training-inside-the-windows-subsystem-for-linux/) which calls out a requirement for Windows 10 build 20150.

Are you able to share where you got the impression that Windows 10 build 19041 was sufficient?

https://aka.ms/wsl2kernel provides the latest _release_ kernel, 4.19.104. [The MS Docs](https://docs.microsoft.com/en-us/windows/wsl/kernel-release-notes) note that 4.19.121 is a pre-release, and also note that this is the version that [adds GPU virtualisation support](https://github.com/microsoft/WSL2-Linux-Kernel/compare/4.19.104-microsoft-standard...4.19.121-microsoft-standard). I would guess that 4.19.121 is only offered by Windows Update for Windows 10 builds after 19041, but I don't know how to view such information in the Update Catalog.

**Comment by levicki** [comment]
@TBBle It seems that I have confused two things -- one is WSL 2 support itself which should have been generally available in build 19041 according to [this Microsoft blog post](https://devblogs.microsoft.com/commandline/wsl2-will-be-generally-available-in-windows-10-version-2004/), and another one is GPU support.

I have assumed that being able to install WSL 2 and kernel 4.9.121 on build 19041 also means that GPU support will be available provided I install adequate NVIDIA drivers (455.38).

Is my assumption wrong? Do builds 20145, 20149, 20150 change WDDM model or virtualization platform to enable WSL 2 GPU support or should this work in build 19041 as well?

The [Windows Insider changelog](https://docs.microsoft.com/en-us/windows-insider/at-home/active-dev-branch) does not suggest any other GPU, WDDM, or platform virtualization related changes between 19041 and 20150.

Clarification would be most appreciated.

**Comment by TBBle** [comment]
From my reading, the missing thing for GPU virtualisation in WSL2 is indeed that Windows 10 Build 20150 was the first release with WDDM 2.9. [Windows 10 2004 upgraded _to_ WDDM 2.7](https://docs.microsoft.com/en-us/windows-hardware/drivers/display/what-s-new-for-windows-10-display-and-graphics-drivers), from [WDDM 2.6 in 1903](https://www.intel.com/content/www/us/en/support/articles/000005654/graphics.html).

[Wikipedia claims WDDM 2.9 will be Windows 10 21H1](https://en.wikipedia.org/wiki/Windows_Display_Driver_Model#WDDM_2.9) (presumably based on it being in the `RS_PRERELEASE` branch post-Windows 2004), which would put WDDM 2.8 in Windows 20H2. But I can't see any _real_ source for that, or in fact any mention of WDDM 2.8 existing. Particularly if there's beta WDDM 2.9 drivers out from AMD, Intel, and NVIDIA already.

**Comment by levicki** [comment]
@TBBle Thanks for the clarification. It seems that it will be a while until GPU under WSL hits the mainstream. In any case, I am looking forward to it.
