### ISSUE TITLE
How to install perf?

### ISSUE THREAD

**Issue by heckad** [microsoft/WSL2-Linux-Kernel#137]
I tried to install `linux-tools-common` and after this I got 
```
WARNING: perf not found for kernel 4.19.104-microsoft

  You may need to install the following packages for this specific kernel:
    linux-tools-4.19.104-microsoft-standard
    linux-cloud-tools-4.19.104-microsoft-standard

  You may also want to install one of the following packages to keep up to date:
    linux-tools-standard
    linux-cloud-tools-standard
```
but `linux-tools-4.19.104-microsoft-standard` or `linux-cloud-tools-4.19.104-microsoft-standard` not found in repo. What to do?

**Comment by WSLUser** [comment]
Your distro is likely expecting a newer kernel. Try out the 5.4 branch or if you want to be on the latest, use 5.8.7 with my config: https://github.com/microsoft/WSL2-Linux-Kernel/pull/176

**Comment by heckad** [comment]
I installed ubuntu from Microsoft store. How to update the kernel correctly now?

**Comment by WSLUser** [comment]
Grab the msi. They updated it to 4.19.128. You may also need kernel options enabled that aren't currently

**Comment by heckad** [comment]
Please, give me ref where I cant download this msi.

**Comment by sileshn** [comment]
"Updating the WSL 2 Linux kernel | Microsoft Docs" https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel#download-the-linux-kernel-update-package

**Comment by heckad** [comment]
Updated but it didn't solve the problem.

**Comment by PvdBerg1998** [comment]
This may help: https://stackoverflow.com/questions/60237123/is-there-any-method-to-run-perf-under-wsl

**Comment by heckad** [comment]
@PvdBerg1998, Thank you very much!
