### ISSUE TITLE
Can't compile v5.5.6

### ISSUE THREAD

**Issue by zhoozhoo** [microsoft/WSL2-Linux-Kernel#144]
It does not include a MICROSOFT/config-wsl-arm64 file. How can I compile it?

**Comment by microhobby** [comment]
@zhoozhoo are you trying to compile from Mainline or from this repository?

**Comment by zhoozhoo** [comment]
@microhobby this repository. I checked out v5.5.6 tab.

**Comment by WSLUser** [comment]
It's coming from mainline Linux. You'll need to either compile mainstream or compile from the 4.19.121 (which has the GPU compute/GUI support added).
