### ISSUE TITLE
Feature request: add official support for running WSL2 image in a custom path

### ISSUE THREAD

**Issue by AlbertSSj** [microsoft/WSL2-Linux-Kernel#147]
To support setups with little space in `C:`, it would be nice to add the possibility to specify the path were to run the WSL2 image.

By hacking a bit it already work as far I can tell. Following the instructions  in https://www.ridingthecrest.com/blog/2020/07/07/wsl2-external-vhdx.html I managed to move Ubuntu to `D:` and all seems fine.

It would be great if this process could become something like:
`wsl --move <Distro> <Path>`

**Comment by jeffcao** [comment]
may be there is another solution:
wsl --export your-distro /d/your-folder/distro-file
then
wsl --import /d/your-folder/your-distro /d/your-folder/distro-file

**Comment by AlbertSSj** [comment]
The first [reply](https://github.com/microsoft/WSL2-Linux-Kernel/issues/147#issuecomment-660432226) provides a perfect solution.
