### ISSUE TITLE
Accessing server used in WSL2 to another device [NOT WORKING]

### ISSUE THREAD

**Issue by justinbalaguer** [microsoft/WSL2-Linux-Kernel#149]
E.g: A create react app running on localhost:3000

Accessing this on my phone through network. It gave me another IP which WSL2 uses. e.g (`On Your Network:  http://172.19.105.12:3000`). This doesn't work, same with the IP of my laptop eg (`192.168.0.100:3000`) this don't work either. This doesn't have any problem with WSL1

**Comment by jeffcao** [comment]
may be you can:
wsl --export your-distro /d/your-folder/distro-file  
then 
wsl --import /d/your-folder/your-distro /d/your-folder/distro-file

**Comment by WSLUser** [comment]
I suggest filing this at https://github.com/microsoft/WSL. This repo isn't intended for bugs like this. This repo is about the kernel support. Also, alot more attention is given in the WSL repo.
