### ISSUE TITLE
WSL2 triggers internet connection sharing (ICS)

### ISSUE THREAD

**Issue by mrT23** [microsoft/WSL2-Linux-Kernel#151]
Do i have to enable internet connection sharing to use WSL2 ?

even if i disable and stop this service, every time i start WSL2, it triggers it manually.
(this is a problem for me, i cant use my VPN service if internet connection sharing is on)

![image](https://user-images.githubusercontent.com/21198860/87867518-536ab180-c996-11ea-9fdc-d0d8804c4eaf.png)

thanks,
Tal

**Comment by WSLUser** [comment]
> i cant use my VPN service if internet connection sharing is on

I suggest filing a bug with your VPN service then. There's obviously a driver issue. You need ICS or WSL2 can't have it's own IP addresses. This goes for Hyper-V and any other VM software. I use stock OpenVPN and it works just fine.

**Comment by mrT23** [comment]
it is not uncommon in organizations and companies to disable the usage ICS due to security reasons.

thanks for the answer

**Comment by Efreak** [comment]
@WSLUser 

> You need ICS or WSL2 can't have it's own IP addresses. This goes for Hyper-V and any other VM software.

Virtualbox and other VM software will work perfectly fine without ICS enabled. Similarly, there are multiple ways to configure networking, of which a router with DHCP server is only one.
