### ISSUE TITLE
Windows Update offering "update" of WSL2

### ISSUE THREAD

**Issue by levicki** [microsoft/WSL2-Linux-Kernel#154]
This is more a Windows Update issue I guess, but still related. Perhaps you could pass the feedback to the proper team.

I am running Windows 10 Pro Version 2004 (10.0.19041.388).

I had manually installed WSL2 4.19.121 from a MSI package.

Windows Update just offered me to "update" it to 4.19.104. When clicking Update it failed with error code `0x80070643`.

After manually uninstalling 4.19.121 from Programs and Features it was able to install 4.19.104 from Windows Update.

Moreover, I had the same setup on my home PC and there it didn't offer the "update".

I understand that 4.19.121 was not official at the time I installed it, but maybe Windows Update shouldn't offer to install things with lower version number and then fail miserably.

**Comment by TBBle** [comment]
I don't think this was related to downgrading specifically, #127 is the same error code for people with Windows Insider builds upgrading their kernel via Windows Update to 4.19.121.1. So probably something is not working correctly with transitioning from MSI-installed kernel to Windows Update-installed kernels.

**Comment by levicki** [comment]
@TBBle My point was that Windows Update shouldn't offer lower version of anything as an "update" on principle.

I had this same situation happen today on two brand new HP ProBook 440 G7 laptops with Windows 10 Version 2004 where Windows Update "upgraded" Intel Display drivers from version **27.20.100.8336** which I preinstalled in our corporate image to version **27.20.100.8190** -- the one I used was released on **2020-06-26** and the "updated" one was released on **2020-05-05**.

I apologize for using this ticket to mention it, but IMO it is related to the WU's obvious inability to compare version numbers and dates correctly in both cases and leave well enough alone until it has something newer and/or better to offer.

**Comment by TBBle** [comment]
Yeah, then this is definitely the wrong place to raise it. Windows Update is clearly offering the newest one it knows about per the Update Catalog; in the Kernel case, 4.19.121.1 is not offered to Windows 10.0.19041, but is offered for newer Windows builds, as mentioned in #127, so the newest it offers is 4.19.104. Sadly the [Update Catalog listings for the WSL2 kernel](https://www.catalog.update.microsoft.com/Search.aspx?q=Windows%20Subsystem%20for%20Linux%20Update) doesn't show what constraints are applied to specific updates.

Similarly for the Intel drivers, the [Update Catalog doesn't know about the version 27.20.100.8336](https://www.catalog.update.microsoft.com/Search.aspx?q=27.20.100.8336), but does know about [version 27.20.100.8190](https://www.catalog.update.microsoft.com/Search.aspx?q=27.20.100.8190). It looks like the latest [WDDM 2.7 driver it knows about is 27.20.100.8280](https://www.catalog.update.microsoft.com/Search.aspx?q=27.20.100.*) so it's still going to offer to install that.

I think your pain-point is that Windows Update doesn't necessarily know about things it didn't install, so it doesn't have any reason to not offer you a downgrade if it doesn't know you don't have anything newer. I actually suspect from poking around that the WU error 0x80070643 is related to WU failing to detect an existing version of something, and hence not uninstalling it correctly before trying to install an update, and in this case, that same failure-to-detect also caused it to offer you a downgrade, thinking it was a new install, or update from some older version.

That would also explain why this didn't happen on your home PC, where I guess WU _did_ see the local version, decide it was newer than what it offered, and hence didn't offer the update.

I'm not sure though; it's definitely not in my area of expertise, and this isn't the Windows Update issue-tracker anyway. ^_^

**Comment by levicki** [comment]
> so it doesn't have any reason to not offer you a downgrade if it doesn't know you don't have anything newer.

How about not breaking a working install? Would that qualify as a good enough reason? I hope the question doesn't come off too snarky :-)

> this isn't the Windows Update issue-tracker anyway.

Is there such a thing though? It would be great if all Windows stuff had issue trackers on GitHub. Although, given how long the bug I reported in .Net Framework is not being resolved I shouldn't hold my breath.

Thanks for the explanation anyway, feel free to close the issue I just wanted to let you know of the problem some people might be facing.

**Comment by AleCx4** [comment]
May I ask where exactly did you get the msi for 4.19.121? every time I try to do this i get 4.19.104 and I have been trying to get xx.121 for days now. And the msi provided here does not work: https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel

**Comment by TBBle** [comment]
@levicki 
> I hope the question doesn't come off too snarky :-)

It does come off as a bit snarky. -_-

Windows Update isn't magic. It doesn't know that your current install is working, if it doesn't know about it, and doesn't know that it'll break it by replacing something it doesn't know about. It does seem like it _should_ know about it, but I don't know how Windows Update determines what's already installed. It's possible for the Intel driver case that the pre-install mechanism didn't set some registry key that Windows Update relies on to know if that thing had been installed, and what version of it had been installed.

I'm not sure that "There isn't a Window Update bug tracker" is a good rationale for "make noise about Windows Update on a different bug tracker from the same (large) company".

**Comment by TBBle** [comment]
@AleCx4 You can grab the update from the [Microsoft Update Catalog](https://www.catalog.update.microsoft.com/Search.aspx?q=Windows%20Subsystem%20for%20Linux%20Update). It'll download a .cab file, and inside that is the .MSI file you want. Althugh I haven't tested this myself.

If you're on Windows 10 2004 or Windows Server 2004, be aware that MS are not publishing the 4.19.121.1 kernel for that version, so it's possible (but not likely, from poking at the source) that there's something in there that doesn't work with the current Windows 10 release. If you're using an Insider build of 21H1, then Windows Update should already have offered you the 4.19.121.1 update.

**Comment by levicki** [comment]
@TBBle 

>It does seem like it should know about it, but I don't know how Windows Update determines what's already installed.

Given that I installed the MSI by downloading it from Windows Update Catalog and extracting it from the CAB file as you describe in your next comment I think Windows Update should know what is installed. After all, for any KB hotfix manually installed from Windows Update Catalog it knows, why not for this?

Version 4.19.104 downloadable from [https://aka.ms/wsl2kernel](https://docs.microsoft.com/en-us/windows/wsl/wsl2-kernel) as well as the ones downloadable from Windows Update Catalog and Windows Update servers has an MSI ProductCode of `{9F858BB9-156F-4C4C-9295-0A06CA83D17C}` so essentially, those MSI packages are identical between all those sources.

On the other hand, current version of 4.19.121.1 kernel from Windows Update Catalog has an MSI ProductCode of `{93E5F4A6-8337-49F7-9BBC-94A82A5C2F80}`. That might explain why Windows Update did not see it (given it is not supposed to be there for Windows 10 Version 2004 which just raises the question why I was allowed to install that MSI to begin with), did not attempt to remove it before installing 4.19.104, and ultimately failed with the error code mentioned.

> It's possible for the Intel driver case that the pre-install mechanism didn't set some registry key that Windows Update relies on to know if that thing had been installed, and what version of it had been installed.

DISM driver integration into install.wim just allows the OS to find and install the driver during hardware detection phase of Windows Setup and driver setup process is identical. IMO, that's just the case of disregarding date and version of the existing driver when deciding whether to offer an update or not.

> I'm not sure that "There isn't a Window Update bug tracker" is a good rationale for "make noise about Windows Update on a different bug tracker from the same (large) company".

I apologize if my question "Is there such a thing though?" came off as a rationalization of my own behavior. What I meant is that I would genuinely appreciate being able to submit such feedback to more appropriate channels.

Sorry for all the noise.
