### ISSUE TITLE
Can't reclaim memory in custom-built kernel

### ISSUE THREAD

**Issue by rekaerst** [microsoft/WSL2-Linux-Kernel#165]
I built a Linux 5.7.11 kernel for WSL2 because I need better support for recent hardware ( newest ryzen processors).
I built my custom kernel with this Microsoft's configuration and the new option in kernel 5.7.11 was set to default.
Everything works fine in my build except memory reclamation.

According to Microsoft, starting with Windows OS Build 19013, that memory which is no longer needed by the W would be able to get released back to the host and this feature is powered by a kernel patch. [[source]](https://devblogs.microsoft.com/commandline/memory-reclaim-in-the-windows-subsystem-for-linux-2/) But for some reason, this feature doesn't work in my custom-built kernel. Even though WSL2 still claims that it was performing memory compaction in the background.

Can this problem be solved by applying the patches to the kernel source tree?

**Comment by sirredbeard** [comment]
> I need better support for recent hardware ( newest ryzen processors)

Are you having issues with existing kernels or are you just trying to maximize performance?

If you want a more recent kernel you can grab this 5.4 https://github.com/microsoft/WSL2-Linux-Kernel/commit/f7de01b95a3967f02676e71ec6ea3eca0998fbbd

> is powered by a kernel patch

I don't believe the WSL memory kernel patch has been upstreamed into the main kernel, it is an out of tree patch, so you will need to manually import to your kernel before building.

**Comment by sirredbeard** [comment]
cc https://github.com/microsoft/WSL/issues/5695

**Comment by rekaerst** [comment]
Linux-msft-5.4.42 don't reclaim memory too.
I think that [mm and virtio-balloon patch](https://patchwork.kernel.org/patch/11169051/) has been upstreamed into the main kernel. It's in the source tree from kernel.org.

**Comment by microhobby** [comment]
@rekaerst check the info from this video https://youtu.be/eE8QPiTIOdE

As @sirredbeard pointed it's not on mainline yet, is work in progress on LKML. So if you want to use it you will have to apply it on your custom Kernel or use the Microsoft downstream Kernel.

**Comment by rekaerst** [comment]
@microhobby thanks for helping 

I applied those patches to Kernel 5.8-rc7 but I get this error in the compilation time
 ```
drivers/hv/hv_balloon.c: In function ‘enable_page_reporting’:
drivers/hv/hv_balloon.c:1588:11: error: ‘struct hv_dynmem_device’ has no member named ‘pr_dev_info’
 1588 |  dm_device.pr_dev_info.report = hv_free_page_report;
      |           ^
drivers/hv/hv_balloon.c:1589:42: error: ‘struct hv_dynmem_device’ has no member named ‘pr_dev_info’
 1589 |  ret = page_reporting_register(&dm_device.pr_dev_info);
      |                                          ^
drivers/hv/hv_balloon.c:1591:12: error: ‘struct hv_dynmem_device’ has no member named ‘pr_dev_info’
 1591 |   dm_device.pr_dev_info.report = NULL;
      |            ^
drivers/hv/hv_balloon.c: In function ‘disable_page_reporting’:
drivers/hv/hv_balloon.c:1601:15: error: ‘struct hv_dynmem_device’ has no member named ‘pr_dev_info’
 1601 |  if (dm_device.pr_dev_info.report) {
      |               ^
drivers/hv/hv_balloon.c:1602:39: error: ‘struct hv_dynmem_device’ has no member named ‘pr_dev_info’
 1602 |   page_reporting_unregister(&dm_device.pr_dev_info);
      |                                       ^
drivers/hv/hv_balloon.c:1603:12: error: ‘struct hv_dynmem_device’ has no member named ‘pr_dev_info’
 1603 |   dm_device.pr_dev_info.report = NULL;
      |            ^
make[2]: *** [scripts/Makefile.build:281: drivers/hv/hv_balloon.o] Error 1
make[1]: *** [scripts/Makefile.build:497: drivers/hv] Error 2
make: *** [Makefile:1756: drivers] Error 2
make: *** Waiting for unfinished jobs....
```

**Comment by rekaerst** [comment]
Thanks a lot, now the kernel can report Unused Memory

**Comment by WSLUser** [comment]
I'd like to add that adding the Clear Linux out of tree patches should help as well. I'd check those to the one created by MS and do a comparison.
