### ISSUE TITLE
Fail to get WSL update 4.19.104 for ARM64

### ISSUE THREAD

**Issue by wangfys** [microsoft/WSL2-Linux-Kernel#183]
Hello! I am a Surface Pro X user. I have just updated to Windows 10 2004 and I'm excited to install WSL2.

After installing WSL2, I received 'Windows Subsystem for Linux update 4.19.104' in Windows Update. I tried to install it and got an download error. All other updates are downloaded and installed successfully so I think there is nothing wrong with my Internet connection.

Is the update for ARM64 not ready? I noticed that all feature updates and quality updates are marked as 'for ARM64', but this update belongs to other updates and doesn't contains information about architecture. I guess Windows Update found such an update but failed to download the ARM64 version because it doesn't exist.

**Comment by Biswa96** [comment]
You could download a Windows Update file from Microsoft Update Catalog. Follow these steps:

1. Go to this website https://www.catalog.update.microsoft.com/Search.aspx?q=wsl
2. Click on the Download button of Linux kernel version you want. 
3. There will be a popup window. Select the package as per your CPU architecture, here ARM64.
4. It will be downloaded as CAB file. Open it. Extract the MSI file. Install the MSI file.

**Comment by wangfys** [comment]
@Biswa96 

Thank you very much. 

Windows Update is really mysterious. Still don't know why it failed to download the update by itself.

I installed the 4.19.128 update directly and it still told me failed to install 4.19.104 update. I uninstalled 4.19.128 update and then installed 4.19.104. The problem is solved.
