### ISSUE TITLE
Feature Request-? :Why are the system CDROMs' not getting scanned into /dev 

### ISSUE THREAD

**Issue by mxdog** [microsoft/WSL2-Linux-Kernel#193]
I just updated to wsl2 because I read that you now had full support for block devices. I was very disappointed to see that all my physical hard drives represented but neither of my dvd/bluray. one is on a sata and the other is usb . I know I can mount them with the drvfs driver but I would really love to see them as Linux devices for forensics and block work like using ddrescue ,dd  ...etc. and a myriad of other uses. A little slow in my case would not be an issue.

***CAUTION***
( small rant not part of the request )
I guess I am a little confused because from what I read I thought that with the full kernel you would be implementing udev and pci buss scans like a real Linux machine or VM  would (at least for USB), even if they are dummied through an abstract-translation/driver layer.

 I am also confused because it looks like you are moving the whole project to basically a VM  ( because we have to enable VirtualMachinePlatform ) which we have had for years and years which makes WSL2 convenient but redundant in many ways and not a whole lot different then just firing up virtualbox or one it's kin and using raw devices at least in that case I have access to any usb devices I care to use .

**Comment by WSLUser** [comment]
Take a look at the README for https://github.com/microsoft/WSL, the official place to be filing issues for WSL and WSL2. This repo is for hosting the kernel. Read the MS blogs and documentation.

**Comment by mxdog** [comment]
huh ? devices integration isn't a kernel issue ? if you are hosting the kernel then native devices are part of that ...

Ok, will cut and paste this over there ...
