### ISSUE TITLE
Can't start docker in wsl2

### ISSUE THREAD

**Issue by sateeshmachineni** [microsoft/WSL2-Linux-Kernel#20]
i am using windows 10 home and using ubuntu distro from windows store.I  have downloaded sql2019  and when i try to start the container using below command.

docker start sql2019

i get below error.

Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:303: getting the final child's pid from pipe caused \"EOF\"": unknown
Error: failed to start containers: sql12019

Any ideas ..

below is the log from docker

`time="2019-08-04T17:21:04.176392900+05:30" level=info msg="libcontainerd: started new containerd process" pid=2472
time="2019-08-04T17:21:04.177051300+05:30" level=info msg="parsed scheme: \"unix\"" module=grpc
time="2019-08-04T17:21:04.177123000+05:30" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
time="2019-08-04T17:21:04.177255500+05:30" level=info msg="ccResolverWrapper: sending new addresses to cc: [{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}]" module=grpc
time="2019-08-04T17:21:04.177335200+05:30" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
time="2019-08-04T17:21:04.177704100+05:30" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc420071930, CONNECTING" module=grpc
time="2019-08-04T17:21:04.228114700+05:30" level=info msg="starting containerd" revision= version="1.2.6-0ubuntu1~18.04.2" 
time="2019-08-04T17:21:04.228733800+05:30" level=info msg="loading plugin "io.containerd.content.v1.content"..." type=io.containerd.content.v1 
time="2019-08-04T17:21:04.228806000+05:30" level=info msg="loading plugin "io.containerd.snapshotter.v1.btrfs"..." type=io.containerd.snapshotter.v1 
time="2019-08-04T17:21:04.228959400+05:30" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.btrfs" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter" 
time="2019-08-04T17:21:04.228988400+05:30" level=info msg="loading plugin "io.containerd.snapshotter.v1.aufs"..." type=io.containerd.snapshotter.v1 
time="2019-08-04T17:21:04.250057100+05:30" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.aufs" error="modprobe aufs failed: "modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-18945-Microsoft/modules.dep.bin'\nmodprobe: FATAL: Module aufs not found in directory /lib/modules/4.4.0-18945-Microsoft\n": exit status 1" 
time="2019-08-04T17:21:04.250157300+05:30" level=info msg="loading plugin "io.containerd.snapshotter.v1.native"..." type=io.containerd.snapshotter.v1 
time="2019-08-04T17:21:04.250478000+05:30" level=info msg="loading plugin "io.containerd.snapshotter.v1.overlayfs"..." type=io.containerd.snapshotter.v1 
time="2019-08-04T17:21:04.251233900+05:30" level=info msg="loading plugin "io.containerd.snapshotter.v1.zfs"..." type=io.containerd.snapshotter.v1 
time="2019-08-04T17:21:04.251459600+05:30" level=warning msg="failed to load plugin io.containerd.snapshotter.v1.zfs" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter" 
time="2019-08-04T17:21:04.251491100+05:30" level=info msg="loading plugin "io.containerd.metadata.v1.bolt"..." type=io.containerd.metadata.v1 
time="2019-08-04T17:21:04.251536200+05:30" level=warning msg="could not use snapshotter zfs in metadata plugin" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter" 
time="2019-08-04T17:21:04.251558000+05:30" level=warning msg="could not use snapshotter btrfs in metadata plugin" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter" 
time="2019-08-04T17:21:04.251576100+05:30" level=warning msg="could not use snapshotter aufs in metadata plugin" error="modprobe aufs failed: "modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-18945-Microsoft/modules.dep.bin'\nmodprobe: FATAL: Module aufs not found in directory /lib/modules/4.4.0-18945-Microsoft\n": exit status 1" 
time="2019-08-04T17:21:04.259519400+05:30" level=info msg="loading plugin "io.containerd.differ.v1.walking"..." type=io.containerd.differ.v1 
time="2019-08-04T17:21:04.259572600+05:30" level=info msg="loading plugin "io.containerd.gc.v1.scheduler"..." type=io.containerd.gc.v1 
time="2019-08-04T17:21:04.259643500+05:30" level=info msg="loading plugin "io.containerd.service.v1.containers-service"..." type=io.containerd.service.v1 
time="2019-08-04T17:21:04.259735600+05:30" level=info msg="loading plugin "io.containerd.service.v1.content-service"..." type=io.containerd.service.v1 
time="2019-08-04T17:21:04.259767000+05:30" level=info msg="loading plugin "io.containerd.service.v1.diff-service"..." type=io.containerd.service.v1 
time="2019-08-04T17:21:04.259793900+05:30" level=info msg="loading plugin "io.containerd.service.v1.images-service"..." type=io.containerd.service.v1 
time="2019-08-04T17:21:04.259819300+05:30" level=info msg="loading plugin "io.containerd.service.v1.leases-service"..." type=io.containerd.service.v1 
time="2019-08-04T17:21:04.259858900+05:30" level=info msg="loading plugin "io.containerd.service.v1.namespaces-service"..." type=io.containerd.service.v1 
time="2019-08-04T17:21:04.259922400+05:30" level=info msg="loading plugin "io.containerd.service.v1.snapshots-service"..." type=io.containerd.service.v1 
time="2019-08-04T17:21:04.259959900+05:30" level=info msg="loading plugin "io.containerd.runtime.v1.linux"..." type=io.containerd.runtime.v1 
time="2019-08-04T17:21:04.260350100+05:30" level=info msg="loading plugin "io.containerd.runtime.v2.task"..." type=io.containerd.runtime.v2 
time="2019-08-04T17:21:04.260658700+05:30" level=info msg="loading plugin "io.containerd.monitor.v1.cgroups"..." type=io.containerd.monitor.v1 
time="2019-08-04T17:21:04.261796900+05:30" level=info msg="loading plugin "io.containerd.service.v1.tasks-service"..." type=io.containerd.service.v1 
time="2019-08-04T17:21:04.261853100+05:30" level=info msg="loading plugin "io.containerd.internal.v1.restart"..." type=io.containerd.internal.v1 
time="2019-08-04T17:21:04.261915700+05:30" level=info msg="loading plugin "io.containerd.grpc.v1.containers"..." type=io.containerd.grpc.v1 
time="2019-08-04T17:21:04.261943100+05:30" level=info msg="loading plugin "io.containerd.grpc.v1.content"..." type=io.containerd.grpc.v1 
time="2019-08-04T17:21:04.261967100+05:30" level=info msg="loading plugin "io.containerd.grpc.v1.diff"..." type=io.containerd.grpc.v1 
time="2019-08-04T17:21:04.261990500+05:30" level=info msg="loading plugin "io.containerd.grpc.v1.events"..." type=io.containerd.grpc.v1 
time="2019-08-04T17:21:04.262013600+05:30" level=info msg="loading plugin "io.containerd.grpc.v1.healthcheck"..." type=io.containerd.grpc.v1 
time="2019-08-04T17:21:04.262036900+05:30" level=info msg="loading plugin "io.containerd.grpc.v1.images"..." type=io.containerd.grpc.v1 
time="2019-08-04T17:21:04.262060000+05:30" level=info msg="loading plugin "io.containerd.grpc.v1.leases"..." type=io.containerd.grpc.v1 
time="2019-08-04T17:21:04.262083400+05:30" level=info msg="loading plugin "io.containerd.grpc.v1.namespaces"..." type=io.containerd.grpc.v1 
time="2019-08-04T17:21:04.262106400+05:30" level=info msg="loading plugin "io.containerd.internal.v1.opt"..." type=io.containerd.internal.v1 
time="2019-08-04T17:21:04.262254000+05:30" level=info msg="loading plugin "io.containerd.grpc.v1.snapshots"..." type=io.containerd.grpc.v1 
time="2019-08-04T17:21:04.262304100+05:30" level=info msg="loading plugin "io.containerd.grpc.v1.tasks"..." type=io.containerd.grpc.v1 
time="2019-08-04T17:21:04.262331400+05:30" level=info msg="loading plugin "io.containerd.grpc.v1.version"..." type=io.containerd.grpc.v1 
time="2019-08-04T17:21:04.262366700+05:30" level=info msg="loading plugin "io.containerd.grpc.v1.introspection"..." type=io.containerd.grpc.v1 
time="2019-08-04T17:21:04.264504500+05:30" level=info msg=serving... address="/var/run/docker/containerd/containerd-debug.sock" 
time="2019-08-04T17:21:04.265226700+05:30" level=info msg=serving... address="/var/run/docker/containerd/containerd.sock" 
time="2019-08-04T17:21:04.265292800+05:30" level=info msg="containerd successfully booted in 0.038083s" 
time="2019-08-04T17:21:04.270829100+05:30" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc420071930, READY" module=grpc
time="2019-08-04T17:21:04.285158300+05:30" level=info msg="parsed scheme: \"unix\"" module=grpc
time="2019-08-04T17:21:04.285286800+05:30" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
time="2019-08-04T17:21:04.285447000+05:30" level=info msg="parsed scheme: \"unix\"" module=grpc
time="2019-08-04T17:21:04.285488500+05:30" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
time="2019-08-04T17:21:04.285751600+05:30" level=info msg="ccResolverWrapper: sending new addresses to cc: [{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}]" module=grpc
time="2019-08-04T17:21:04.285814100+05:30" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
time="2019-08-04T17:21:04.285894300+05:30" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc420184bc0, CONNECTING" module=grpc
time="2019-08-04T17:21:04.285808700+05:30" level=info msg="ccResolverWrapper: sending new addresses to cc: [{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}]" module=grpc
time="2019-08-04T17:21:04.285962700+05:30" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
time="2019-08-04T17:21:04.286038200+05:30" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc420184cf0, CONNECTING" module=grpc
time="2019-08-04T17:21:04.286181000+05:30" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc420184bc0, READY" module=grpc
time="2019-08-04T17:21:04.286356300+05:30" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc420184cf0, READY" module=grpc
time="2019-08-04T17:21:04.310442600+05:30" level=info msg="[graphdriver] using prior storage driver: overlay2"
time="2019-08-04T17:21:04.323672900+05:30" level=info msg="Graph migration to content-addressability took 0.00 seconds"
time="2019-08-04T17:21:04.323909100+05:30" level=warning msg="Your kernel does not support cgroup memory limit"
time="2019-08-04T17:21:04.323947000+05:30" level=warning msg="Unable to find cpu cgroup in mounts"
time="2019-08-04T17:21:04.323967700+05:30" level=warning msg="Unable to find blkio cgroup in mounts"
time="2019-08-04T17:21:04.323995600+05:30" level=warning msg="Unable to find cpuset cgroup in mounts"
time="2019-08-04T17:21:04.324079600+05:30" level=warning msg="mountpoint for pids not found"
time="2019-08-04T17:21:04.324593400+05:30" level=info msg="Loading containers: start."
time="2019-08-04T17:21:04.345946600+05:30" level=warning msg="Running modprobe nf_nat failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-18945-Microsoft/modules.dep.bin'\nmodprobe: WARNING: Module nf_nat not found in directory /lib/modules/4.4.0-18945-Microsoft`, error: exit status 1"
time="2019-08-04T17:21:04.365504200+05:30" level=warning msg="Running modprobe xt_conntrack failed with message: `modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.0-18945-Microsoft/modules.dep.bin'\nmodprobe: WARNING: Module xt_conntrack not found in directory /lib/modules/4.4.0-18945-Microsoft`, error: exit status 1"
time="2019-08-04T17:21:04.770544200+05:30" level=info msg="stopping event stream following graceful shutdown" error="<nil>" module=libcontainerd namespace=moby
time="2019-08-04T17:21:04.772676400+05:30" level=info msg="stopping healthcheck following graceful shutdown" module=libcontainerd
time="2019-08-04T17:21:04.772802700+05:30" level=info msg="stopping event stream following graceful shutdown" error="context canceled" module=libcontainerd namespace=plugins.moby
time="2019-08-04T17:21:04.777660400+05:30" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc420184cf0, TRANSIENT_FAILURE" module=grpc
time="2019-08-04T17:21:04.777903600+05:30" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc420184cf0, CONNECTING" module=grpc
Error starting daemon: Error initializing network controller: error obtaining controller instance: failed to create NAT chain DOCKER: iptables failed: iptables -t nat -N DOCKER: iptables v1.6.1: can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
 (exit status 3)
`

**Comment by marceloc312** [comment]
Same here..

**Comment by sateeshmachineni** [comment]
Running Terminal as Admin worked.
