### ISSUE TITLE
/dev/kvm is not available in WSL2?

### ISSUE THREAD

**Issue by ThomsonTan** [microsoft/WSL2-Linux-Kernel#209]
I think the latest WSL2 kernel is built with KVM enabled? But I don't see /dev/kvm in my Ubuntu distro running on WSL2, do I need enable nested virtualization to see it? My WSL Linux kernel version is 4.19.128-microsoft-standard.

**Comment by Biswa96** [comment]
Try `zcat /proc/config.gz | grep -i kvm` command ad you will get if it is enabled or not.

**Comment by Biswa96** [comment]
Try `zcat /proc/config.gz | grep -i kvm` command and you will get if it is enabled or not.

**Comment by ThomsonTan** [comment]
It shows as `Y` for all the options like `CONFIG_HAVE_KVM=y`, then how to enable kvm? `/dev/kmsg` has log "kvm: no hardware support".

**Comment by justinkb** [comment]
I don't think this is available unless you are running a fast insider ring build of windows

**Comment by ThomsonTan** [comment]
@justinkb you are right. I am Windows 10 build 19042 which seems doesn't support nested virtualization in WSL2, I upgraded to some latest insider build and got it working (observed `/dev/kvm` in WSL2).
