### ISSUE TITLE
Make : errors in net/ipv4/netfilter/ipt_ECN.c

### ISSUE THREAD

**Issue by Thomas16093** [microsoft/WSL2-Linux-Kernel#224]
Hello,

I was compiling the kernel 4.19.128-microsoft-standard to activate the kvm module in my subsytem.
And after setting the right parameters and run make -j 4, I ran into errors in the file ipt_ECN.c

All the errors are in the file attached below.
[log_compilation.txt](https://github.com/microsoft/WSL2-Linux-Kernel/files/5683216/log_compilation.txt)

From what i see, it shouldn't be my config, but maybe a general error.
I didn't manipulate the setting for the internet modules that this should make.

Is it something I can fix or do I have to wait for a correction ?

**Comment by abdul-farhat** [comment]
> Hello,
> 
> I was compiling the kernel 4.19.128-microsoft-standard to activate the kvm module in my subsytem.
> And after setting the right parameters and run make -j 4, I ran into errors in the file ipt_ECN.c
> 
> All the errors are in the file attached below.
> [log_compilation.txt](https://github.com/microsoft/WSL2-Linux-Kernel/files/5683216/log_compilation.txt)
> 
> From what i see, it shouldn't be my config, but maybe a general error.
> I didn't manipulate the setting for the internet modules that this should make.
> 
> Is it something I can fix or do I have to wait for a correction ?

I had this issue when cloning and compiling in a dir on '/mnt/c/' - some case-insensitive issue.

Try compiling this in a different dir inside ya WSL instance.

**Comment by Thomas16093** [comment]
Hello,

Thanks, yes I tried to compile it in a directory with maybe an issue like that.
I will try with a basic folder and come back with the result.

Thanks, again.

**Comment by Thomas16093** [comment]
Okay,

so after a few try.
I can say that for compiling the kernel inside the WSL instance, I have to place it in the ~ directory.
No test in a /mnt/x drive concluded correctly, even with the most basic folder.
Thanks for your help abdul-farhat.

I can close this issue now.
