### ISSUE TITLE
W:mkconf , W:mdadm Issue

### ISSUE THREAD

**Issue by yashomer1994** [microsoft/WSL2-Linux-Kernel#26]
When I am trying to upgrade to latest kernel in WSL 2 Ubuntu 18.04 , 
I am getting a warning of mkconf and mdadm.
mkconf: MD subsystem is not loaded , thus I cannot scan for arrays.
madam:failed to autogenerate temporary mdadm.conf file .

**Comment by Marietto2008** [comment]
I don't understand if this bug has been fixed. I have got it :

ziomarietto@DESKTOP-N9UN2H3:/mnt/c/Users/marietto2020/Desktop/WSL/WSL/Ubuntu-KVM/4.19.104/WSL2-Linux-Kernel-4.19.104-microsoft-standard$ dir

COPYING        Kbuild    MAINTAINERS  Module.symvers         System.map  built-in.a  drivers   include  kernel  modules.builtin  samples   sound  virt
CREDITS        Kconfig   Makefile     README                 arch        certs       firmware  init     lib     modules.order    scripts   tools  vmlinux
Documentation  LICENSES  Microsoft    README-Microsoft.WSL2  block       crypto      fs        ipc      mm      net              security  usr    vmlinux.o

ziomarietto@DESKTOP-N9UN2H3:/mnt/c/Users/marietto2020/Desktop/WSL/WSL/Ubuntu-KVM/4.19.104/WSL2-Linux-Kernel-4.19.104-microsoft-standard$ sudo make modules_install -j 12
[sudo] password for ziomarietto:

  INSTALL drivers/hid/hid-generic.ko
  INSTALL drivers/hid/hid.ko
  INSTALL drivers/hid/usbhid/usbhid.ko
  INSTALL drivers/net/mii.ko
  INSTALL drivers/net/phy/libphy.ko
  INSTALL drivers/net/usb/asix.ko
  INSTALL drivers/net/usb/ax88179_178a.ko
  INSTALL drivers/net/usb/cdc_ether.ko
  INSTALL drivers/net/usb/cdc_ncm.ko
  INSTALL drivers/net/usb/cdc_subset.ko
  INSTALL drivers/net/usb/net1080.ko
  INSTALL drivers/net/usb/rndis_host.ko
  INSTALL drivers/net/usb/usbnet.ko
  INSTALL drivers/net/usb/zaurus.ko
  INSTALL drivers/usb/class/cdc-acm.ko
  INSTALL drivers/usb/common/usb-common.ko
  INSTALL drivers/usb/core/usbcore.ko
  INSTALL drivers/usb/phy/phy-generic.ko
  INSTALL drivers/usb/serial/ftdi_sio.ko
  INSTALL drivers/usb/serial/usbserial.ko
  INSTALL drivers/usb/storage/usb-storage.ko
  INSTALL drivers/usb/usbip/usbip-core.ko
  INSTALL drivers/usb/usbip/vhci-hcd.ko
  DEPMOD  4.19.104-microsoft-standard

ziomarietto@DESKTOP-N9UN2H3:/mnt/c/Users/marietto2020/Desktop/WSL/WSL/Ubuntu-KVM/4.19.104/WSL2-Linux-Kernel-4.19.104-microsoft-standard$ sudo make install
sh ./arch/x86/boot/install.sh 4.19.104-microsoft-standard arch/x86/boot/bzImage \
        System.map "/boot"
run-parts: executing /etc/kernel/postinst.d/apt-auto-removal 4.19.104-microsoft-standard /boot/vmlinuz-4.19.104-microsoft-standard
run-parts: executing /etc/kernel/postinst.d/initramfs-tools 4.19.104-microsoft-standard /boot/vmlinuz-4.19.104-microsoft-standard
update-initramfs: Generating /boot/initrd.img-4.19.104-microsoft-standard
W: mkconf: MD subsystem is not loaded, thus I cannot scan for arrays.
W: mdadm: failed to auto-generate temporary mdadm.conf file.
run-parts: executing /etc/kernel/postinst.d/pm-utils 4.19.104-microsoft-standard /boot/vmlinuz-4.19.104-microsoft-standard
run-parts: executing /etc/kernel/postinst.d/unattended-upgrades 4.19.104-microsoft-standard /boot/vmlinuz-4.19.104-microsoft-standard
run-parts: executing /etc/kernel/postinst.d/update-notifier 4.19.104-microsoft-standard /boot/vmlinuz-4.19.104-microsoft-standard

ziomarietto@DESKTOP-N9UN2H3:/mnt/c/Users/marietto2020/Desktop/WSL/WSL/Ubuntu-KVM/4.19.104/WSL2-Linux-Kernel-4.19.104-microsoft-standard$ ls /boot
System.map-4.19.104-microsoft-standard  memtest86+.bin  memtest86+_multiboot.bin
initrd.img-4.19.104-microsoft-standard  memtest86+.elf  vmlinuz-4.19.104-microsoft-standard

**Comment by yashomer1994** [comment]
You need WSL2 to install Kernel build , as Only WSL2 supports Linux kernel properly.

**Comment by Marietto2008** [comment]
C:\
λ wsl -l -v
  NAME            STATE           VERSION
* Ubuntu-20.04    Running         2
  Ubuntu          Stopped         2
  Ubuntu-18.04    Stopped         2
  Ubuntu-16.04    Stopped         1

C:\
λ wsl -s  Ubuntu-18.04

C:\
λ wsl -l -v
  NAME            STATE           VERSION
* Ubuntu-18.04    Stopped         2
  Ubuntu          Stopped         2
  Ubuntu-20.04    Stopped         2
  Ubuntu-16.04    Stopped         1

C:\
λ wsl
ziomarietto@DESKTOP-N9UN2H3:/mnt/c$ su
Password:
root@DESKTOP-N9UN2H3:/mnt/c# cd /usr/src
root@DESKTOP-N9UN2H3:/usr/src# ls

4.19.104-microsoft-standard  4.19.104-microsoft-standard.tar.gz
root@DESKTOP-N9UN2H3:/usr/src# cd 4.19.104-microsoft-standard
root@DESKTOP-N9UN2H3:/usr/src/4.19.104-microsoft-standard# ls
COPYING        Kconfig      Microsoft              System.map  certs     fs       kernel           modules.order  security     usr
CREDITS        LICENSES     Module.symvers         arch        crypto    include  lib              net            sound        virt
Documentation  MAINTAINERS  README                 block       drivers   init     mm               samples        startusb.sh  vmlinux
Kbuild         Makefile     README-Microsoft.WSL2  built-in.a  firmware  ipc      modules.builtin  scripts        tools        vmlinux.o

root@DESKTOP-N9UN2H3:/usr/src/4.19.104-microsoft-standard# uname -a
Linux DESKTOP-N9UN2H3 4.19.104-microsoft-standard #1 SMP Thu Apr 30 06:28:22 PDT 2020 x86_64 x86_64 x86_64 GNU/Linux

root@DESKTOP-N9UN2H3:/usr/src/4.19.104-microsoft-standard# ./startusb.sh
modprobe: ERROR: could not insert 'usbcore': Unknown symbol in module, or unknown parameter (see dmesg)
modprobe: ERROR: could not insert 'usbnet': Unknown symbol in module, or unknown parameter (see dmesg)
modprobe: ERROR: could not insert 'cdc_ether': Unknown symbol in module, or unknown parameter (see dmesg)
modprobe: ERROR: could not insert 'rndis_host': Unknown symbol in module, or unknown parameter (see dmesg)
modprobe: ERROR: could not insert 'usbserial': Unknown symbol in module, or unknown parameter (see dmesg)
modprobe: ERROR: could not insert 'usb_storage': Unknown symbol in module, or unknown parameter (see dmesg)
modprobe: ERROR: could not insert 'cdc_acm': Unknown symbol in module, or unknown parameter (see dmesg)
modprobe: ERROR: could not insert 'ftdi_sio': Unknown symbol in module, or unknown parameter (see dmesg)
modprobe: ERROR: could not insert 'vhci_hcd': Unknown symbol in module, or unknown parameter (see dmesg)

**Comment by Marietto2008** [comment]
I'm on wsl2 and I'm running ubuntu 18.04 with kernel 4.19.104. I've compiled the kernel and the usb modules without errors inside wsl2. Errors come only when I make install those modules....

root@DESKTOP-N9UN2H3:/usr/src/4.19.104-microsoft-standard# make modules_install -j 12
  INSTALL drivers/hid/hid-generic.ko
  INSTALL drivers/hid/hid.ko
  INSTALL drivers/hid/usbhid/usbhid.ko
  INSTALL drivers/net/mii.ko
  INSTALL drivers/net/phy/libphy.ko
  INSTALL drivers/net/usb/cdc_ether.ko
  INSTALL drivers/net/usb/rndis_host.ko
  INSTALL drivers/net/usb/usbnet.ko
  INSTALL drivers/usb/class/cdc-acm.ko
  INSTALL drivers/usb/common/usb-common.ko
  INSTALL drivers/usb/core/usbcore.ko
  INSTALL drivers/usb/phy/phy-generic.ko
  INSTALL drivers/usb/serial/ftdi_sio.ko
  INSTALL drivers/usb/serial/usbserial.ko
  INSTALL drivers/usb/storage/usb-storage.ko
  INSTALL drivers/usb/usbip/usbip-core.ko
  INSTALL drivers/usb/usbip/vhci-hcd.ko
  DEPMOD  4.19.104-microsoft-standard

root@DESKTOP-N9UN2H3:/usr/src/4.19.104-microsoft-standard# make install -j 12
sh ./arch/x86/boot/install.sh 4.19.104-microsoft-standard arch/x86/boot/bzImage \
        System.map "/boot"
run-parts: executing /etc/kernel/postinst.d/apt-auto-removal 4.19.104-microsoft-standard /boot/vmlinuz-4.19.104-microsoft-standard
run-parts: executing /etc/kernel/postinst.d/initramfs-tools 4.19.104-microsoft-standard /boot/vmlinuz-4.19.104-microsoft-standard
update-initramfs: Generating /boot/initrd.img-4.19.104-microsoft-standard
W: mkconf: MD subsystem is not loaded, thus I cannot scan for arrays.
W: mdadm: failed to auto-generate temporary mdadm.conf file.
run-parts: executing /etc/kernel/postinst.d/pm-utils 4.19.104-microsoft-standard /boot/vmlinuz-4.19.104-microsoft-standard
run-parts: executing /etc/kernel/postinst.d/unattended-upgrades 4.19.104-microsoft-standard /boot/vmlinuz-4.19.104-microsoft-standard
run-parts: executing /etc/kernel/postinst.d/update-notifier 4.19.104-microsoft-standard /boot/vmlinuz-4.19.104-microsoft-standard

root@DESKTOP-N9UN2H3:/usr/src/4.19.104-microsoft-standard# ./startusb.sh
modprobe: ERROR: could not insert 'usbcore': Unknown symbol in module, or unknown parameter (see dmesg)
modprobe: ERROR: could not insert 'usbnet': Unknown symbol in module, or unknown parameter (see dmesg)
modprobe: ERROR: could not insert 'cdc_ether': Unknown symbol in module, or unknown parameter (see dmesg)
modprobe: ERROR: could not insert 'rndis_host': Unknown symbol in module, or unknown parameter (see dmesg)
modprobe: ERROR: could not insert 'usbserial': Unknown symbol in module, or unknown parameter (see dmesg)
modprobe: ERROR: could not insert 'usb_storage': Unknown symbol in module, or unknown parameter (see dmesg)
modprobe: ERROR: could not insert 'cdc_acm': Unknown symbol in module, or unknown parameter (see dmesg)
modprobe: ERROR: could not insert 'ftdi_sio': Unknown symbol in module, or unknown parameter (see dmesg)
modprobe: ERROR: could not insert 'vhci_hcd': Unknown symbol in module, or unknown parameter (see dmesg)
172.31.112.1

**Comment by yashomer1994** [comment]
install modules first, then install kernel, then modules will work properly, or you can raise issue about drivers in Windows Wsl2 main git repo. They are improving in giving support for drivers.
