### ISSUE TITLE
Cant use systemd

### ISSUE THREAD

**Issue by zyazhb** [microsoft/WSL2-Linux-Kernel#44]
Trying to run as user instance, but the system has not been booted with systemd.

**Comment by diddledan** [comment]
There's a "hack" that I'm working on which I've documented over at https://forum.snapcraft.io/t/snapd-on-wsl2-insiders-only-for-now/13033.

Basically you need to start a new process namespace to get systemd as PID1 and then "enter" that namespace in your shell to be able to use it. I worked on this as an effort to get `snapd` and Snap Packages running in WSL2.

**Comment by Biswa96** [comment]
This is not a Linux kernel issue. This occurs because how WSL2 works. Please see this long running thread https://github.com/microsoft/WSL/issues/994.

**Comment by Biswa96** [comment]
This is not a Linux kernel issue. This occurs because how WSL2 works. Please see this long running thread https://github.com/microsoft/WSL/issues/994. And the workaround was posted by @therealkenc here https://github.com/microsoft/WSL/issues/994#issuecomment-502055417.

**Comment by zyazhb** [comment]
tnx for answer

**Comment by Gsyltc** [comment]
Here is a method to have systemd on Debian. Works for me (works fine with docker, swarm, K8s, etc...)

But it break interrop function (can not used cmd.exe or ps).

[https://github.com/shayne/wsl2-hacks/blob/master/README.md](url)

**Comment by zyazhb** [comment]
Tnx for information, but this feature cost too much for me. Still waiting better solution.
