### ISSUE TITLE
IP_SET and XT_SET to support network policies for a Kubernetes net driver

### ISSUE THREAD

**Issue by chanwit** [microsoft/WSL2-Linux-Kernel#47]
I got an issue to run `weavenet` with network policies on Kubernetes / WSL2.
After investigation, we found that the kernel missing `IP_SET` and `XT_SET` configs for the network policy controller of `weavenet` driver.

To fix this, I put the following configs
```
-# CONFIG_IP_SET is not set
+
+CONFIG_NETFILTER_XT_SET=y
+
+CONFIG_IP_SET=y
+CONFIG_IP_SET_MAX=256
+CONFIG_IP_SET_BITMAP_IP=y
+CONFIG_IP_SET_BITMAP_IPMAC=y
+CONFIG_IP_SET_BITMAP_PORT=y
+
+CONFIG_IP_SET_HASH_IP=y
+CONFIG_IP_SET_HASH_IPMARK=y
+CONFIG_IP_SET_HASH_IPPORT=y
+CONFIG_IP_SET_HASH_IPPORTIP=y
+CONFIG_IP_SET_HASH_IPPORTNET=y
+CONFIG_IP_SET_HASH_IPMAC=y
+CONFIG_IP_SET_HASH_MAC=y
+CONFIG_IP_SET_HASH_NETPORTNET=y
+CONFIG_IP_SET_HASH_NET=y
+CONFIG_IP_SET_HASH_NETNET=y
+CONFIG_IP_SET_HASH_NETPORT=y
+CONFIG_IP_SET_HASH_NETIFACE=y
```

**Comment by Biswa96** [comment]
This is added in WSL/Linux kernel version 4.19.75. See commits on Sep 27, 2019 in linux-msft-wsl-4.19.y branch.

**Comment by chanwit** [comment]
Confirmed to see changes in 8d6871ad36710ad378f41e3249c820bda5367a38

Thank you @Biswa96
