### ISSUE TITLE
Compiled Linux Kernel is not same as in System32

### ISSUE THREAD

**Issue by Biswa96** [microsoft/WSL2-Linux-Kernel#5]
I compiled Linux kernel from this repository as written in README file. But the binary file si not same as in System32 one. Here are the output of `file` commands:

* In System32:

```console
# file /mnt/c/Windows/System32/lxss/tools/kernel
/mnt/c/Windows/System32/lxss/tools/kernel: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, BuildID[sha1]=1cdcda82d3a405575308724a5e303c5738893915, not stripped
```

* Compiled one:

```console
# file arch/x86/boot/bzImage
arch/x86/boot/bzImage: Linux kernel x86 boot executable bzImage, version 4.19.52-microsoft-standard+ (root@A) #1 SMP Sat Jun 29 18:26:18 IST 2019, RO-rootFS, swap_dev 0x7, Normal VGA
```

Am I doing anything wrong? Or incomplete docs?

**Comment by saboya** [comment]
Your executable is compressed (`executable bzImage`), for starters.

**Comment by Biswa96** [comment]
@saboya Thanks for the [hint](https://en.wikipedia.org/wiki/Vmlinux#bzImage). I was under false impression from the output of make command. I though `arch/x86/boot/bzImage` is used in System32. The right one is `vmlinux` binary.
