### ISSUE TITLE
"wsl --set-default-version 2" deosn't work

### ISSUE THREAD

**Issue by francesco1119** [microsoft/WSL2-Linux-Kernel#72]
As you can see form the picture the command `wsl --set-default-version 2` deosn't work.

![WSL](https://user-images.githubusercontent.com/3397477/74595587-93261980-5043-11ea-9968-462cf1359aa9.png)

1) I run` wsl -l` and I have as result 3 different WSL versions: Ubuntu, Debian and Kali-linux.
2) I run `wsl --set-version Debian 2` and I set Debian as the default WSL2; all good, the terminal says Debian was already set as WSL2.
3) I run "wsl --set-default-version 2" and I set Debian WSL2 as default.
4) I run "wsl --list --verbose": Debian is indeed the WSL2 but is not the default.
5) I login into WSL running `bash `and when I'm in I type "lsb_release -a": the OS is definetly Ubuntu and not Debian. 

So how to set WSL2 as default?

**Comment by Nomyfan** [comment]
If you want to set Debian as default distro, try `wsl --set-default Debian`
