### ISSUE TITLE
[Feature Request] Enable User Namespace Feature

### ISSUE THREAD

**Issue by kkimdev** [microsoft/WSL2-Linux-Kernel#8]
Podman requires [user namespace](https://en.wikipedia.org/wiki/Linux_namespaces#User_ID_(user)) feature to operate.

- More context: https://github.com/containers/libpod/issues/3288
- Flag https://cateee.net/lkddb/web-lkddb/USER_NS.html

**Comment by kdrag0n** [comment]
`CONFIG_USER_NS` is enabled in the kernel config: https://github.com/microsoft/WSL2-Linux-Kernel/blob/master/Microsoft/config-wsl#L145

**Comment by kkimdev** [comment]
Actually, we just noticed that as well, we will continue investigate why Podman is not working on WSL 2 at https://github.com/containers/libpod/issues/3288
