### ISSUE TITLE
How can I use nbd in wsl2 

### ISSUE THREAD

**Issue by HuAaron** [microsoft/WSL2-Linux-Kernel#80]
I installed wsl2 on Windows 10 2004, and then install ubuntu. Default to version 2.
**wsl -l -v**
```
  NAME           STATE           VERSION
* Ubuntu         Running         2
  SLES-15-SP1    Running         2

```
When I use lsmod | grep nbd it found nothing. When I try to install it via  
**modprobe nbd**, it reported the error:
```
modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.19.84-microsoft-standard/modules.dep.bin'
modprobe: FATAL: Module nbd not found in directory /lib/modules/4.19.84-microsoft-standard
```
According to https://github.com/microsoft/WSL2-Linux-Kernel/blob/master/Documentation/blockdev/nbd.txt, I suppose nbd is loaded as kernel module, right? How can I make nbd work so that I can use /dev/nbd0 and so on?
Thanks.

**Comment by sileshn** [comment]
Its not enabled in the kernel.

https://github.com/microsoft/WSL2-Linux-Kernel/blob/master/Microsoft/config-wsl#L1406

You can try building  a custom kernel by enabling it.

**Comment by HuAaron** [comment]
> Its not enabled in the kernel.
> 
> https://github.com/microsoft/WSL2-Linux-Kernel/blob/master/Microsoft/config-wsl#L1406
> 
> You can try building a custom kernel by enabling it.

That works. Thanks!

**Comment by IBIT-ZEE** [comment]
is there any other WSL2 Linux distro with NBD ready?
