### ISSUE TITLE
How can i update the kernel to the latest LTS 5.4?

### ISSUE THREAD

**Issue by wanghaiwei** [microsoft/WSL2-Linux-Kernel#82]

**Comment by sileshn** [comment]
You'll obviously have to compile it yourself. If u r interested in a 5.6 rc kernel, google Nathan chancellor on github. He has mainline branch for the wsl2 kernel. I am running a 5.6 rc kernel compiled from his sources.

**Comment by nunix** [comment]
I wrote this, if it can help: https://wsl.dev/wsl2-kernel-zfs/

**Comment by wanghaiwei** [comment]
I've compiled the kernel by myself
