### ISSUE TITLE
Android build failed: build-globs.ninja "exec format error" : has anyone successfully built AOSP?

### ISSUE THREAD

**Issue by thomas-truepic** [microsoft/WSL2-Linux-Kernel#83]
WSL2 cannot run "m nothing" in Android AOSP tree from Qualcomm.

Steps to reproduce:
1. cd <aosp-home>
2. . build/envsetup.sh
3. lunch kona-userdebug
4. make nothing

 "m nothing" is same as "make nothing". 

Build always fail at soong build initialization. Is ninja supported in WSL2? Has anyone managed to build AOSP in WSL2?

Thank you,
Thomas 

------------------------ build log ----------------------------------------
thomas@thomas-truepic:~/foresight-repo/ree/caf$ m nothing
Restriction Checker not present, skipping..
device/qcom/kona/kona.mk:4: warning: TEMPORARY_DISABLE_PATH_RESTRICTIONS: export has been deprecated. It is a global setting. See https://android.googlesource.com/platform/build/+/master/Changes.md#export_keyword.
hardware/qcom/media/conf_files/kona/kona.mk:28: warning: "Enabling codec2.0 SW only for non-generic odm build variant"
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=10
TARGET_PRODUCT=kona
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=kryo300
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv8-2a
TARGET_2ND_CPU_VARIANT=cortex-a75
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.4.0-19041-Microsoft-x86_64-Ubuntu-18.04.4-LTS
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=QKQ1.191219.002
OUT_DIR=out
============================================
20:11:13 soong minibootstrap failed with: exit status 1
FAILED: ninja: ./build/blueprint/bootstrap/build.ninja:11: loading 'out/soong/.minibootstrap/build-globs.ninja': Exec format error
subninja ${myGlobs}
                   ^ near here

**Comment by sileshn** [comment]
I build lineageos on arch and Ubuntu wsl2. Works fine. Need to increase swap to 10gb.

**Comment by thomas-truepic** [comment]
Thank you for the information, Silesh. I increased the pagefile size to 24GB, and still no dice.
BTW, is there another way to increase swap, other than the hint to increase pagefile via Windows System Properties?

**Comment by sileshn** [comment]
You can use the .wslconfig file to specify swap size. I use it to add a custom kernel too.

**Comment by sileshn** [comment]
Which distro are you using?

**Comment by alongcookie** [comment]
same problem when build aosp

**Comment by sileshn** [comment]
Have you setup the build environment? You need to install a few packages for a successful build. This is the procedure for lineageos.

https://forum.xda-developers.com/android/software-hacking/guide-how-to-build-lineageos-15-1-t3750175

**Comment by thomas-truepic** [comment]
Thank you, I'm right nowing fetch AOSP to my WSL-2+Ubuntu18.04 setup. If I can build AOSP, then I will move on to your instruction on LineageOS.

**Comment by thomas-truepic** [comment]
@alongcookie I am seeing same issue building latest AOSP.
Now I am following @sileshn's instructions to try lineageos.


AOSO lunch: selected 27: arm-kryo838-eng
make -j2 nothing.
Does it work? No, same error:
Version:0.9 StartHTML:0000000157 EndHTML:0000000854 StartFragment:0000000223 EndFragment:0000000840 StartSelection:0000000223 EndSelection:0000000840 Windows Terminal
FAILED: ninja: ./build/blueprint/bootstrap/build.ninja:11: loading 'out/soong/.minibootstrap/build-globs.ninja': Exec f
ormat error
subninja ${myGlobs}
               ^ near here
17:34:16 soong minibootstrap failed with: exit status 1

failed to build some targets (23 seconds)

**Comment by ri7erhuang** [comment]
> @alongcookie I am seeing same issue building latest AOSP.
> Now I am following @sileshn's instructions to try lineageos.
> 
> AOSO lunch: selected 27: arm-kryo838-eng
> make -j2 nothing.
> Does it work? No, same error:
> Version:0.9 StartHTML:0000000157 EndHTML:0000000854 StartFragment:0000000223 EndFragment:0000000840 StartSelection:0000000223 EndSelection:0000000840 Windows Terminal
> FAILED: ninja: ./build/blueprint/bootstrap/build.ninja:11: loading 'out/soong/.minibootstrap/build-globs.ninja': Exec f
> ormat error
> subninja ${myGlobs}
> ^ near here
> 17:34:16 soong minibootstrap failed with: exit status 1
> 
> failed to build some targets (23 seconds)

Hi thomas
have you solved this issue?
i encountered the same problem
could you share your solution

**Comment by thomas-truepic** [comment]
No, I am still stuck. I was able to build LineageOS following @sileshn documentation. But not the Android 10 AOSP gerrit repo.   Again, this is only a problem in WSL. Ubuntu 21 builds fine.
